language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: fPibNLV5iLdwqiiG+ngpoSSCi5T6y5PtNLFRuyZdH1KddJ9/8nFVyvrkKEhQ4I2UxLR2Ik5Y+KCwkbBNWpLY9cy05TJ/3qC0TZw+1AII5A304kcWOc4wx5F5z/upFa9mvH5EpjUfKhSvBgJbnjErp63l+6U4O1bPlDV0ktANBRuy3umXZCjGkWZJ9y9fx0WU8TEqAmzlFQXCLj0iGd11drBDcFr9rJdESWrO2v28kLpFkCWvbKRX9tJ8ov7by40G0VSrZurTj+mfzpHV3Q0Gbj1izzN2TfV5fPF22CwvEzepJ2JwWfJdei0/TwgU0V6gNOeix8SlF0ji98u0k93J8Fmv2BE+RLXcyyUK7Mak/M6WTqjmx3f953BM1PGd0APEuYVj0UgVtzpMbb/9Hj4Iil1M2oRrlnTE3S5igpN92tuilTzLtL+pAD+7TTPEXesr7tnmTNf+xMctt8cqdRQzOSbt27YezJnGC35XrqYpNj9L37WTgvS25etD2pmmvmTPxyyq1sHG51nKHodjMk8Zte7w9A9nSq8gfKIizkXElzWz5j8FKPzcKSYRyBkPgtOrp/NRFty6YLZ5VjQtobkZLnGNt4oyt6O3/ni+PyTedrUmt7TprUemDogK20qPdF0YP5pmqust6ZDTVDJQvKqSDIbHbz1ZrjE4qgehwOsUwtY=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
